---
version: 2.1
jobs:
  build:
    docker: 
    - image: alpine:3.10.0
    steps:
    - checkout
    - run:
        command: |
          apk add git
          if ! git diff --quiet master $CIRCLE_SHA1 foo; then
            echo "foo is updated"
          else
            echo "foo isn't updated"
          fi
